# Generated by Django 3.2.9 on 2021-11-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0003_auto_20211106_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(default='43.768970'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon',
            field=models.FloatField(default='-79.380150'),
        ),
    ]
